version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: oc_postgres-db
    environment:
      POSTGRES_USER: opususer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_connect_db
    volumes:
      - ./datas/pg-db:/var/lib/postgresql/data
      - ./keycloak/init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: oc_keycloak
    entrypoint: /bin/sh
    command: -c "/wait-for-it.sh postgres:5432 --timeout=60 --strict -- /opt/keycloak/bin/kc.sh start-dev"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: opususer
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/wait-for-it.sh:/wait-for-it.sh
  